# creation rules are evaluated sequentially, the first match wins

# WARNING: DO NOT PUT DECRYPTION RULES IN HERE
# KAPP-CONTROLLER WILL IGNORE THIS FILE, SO IMPORTANT TO ONLY
# DO ENCRYPTION RULES.
creation_rules:
  - pgp: '041305B172A31BAE0459112C726238C01C0E1A2C'