#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata":{"name":"external-dns"}})
---
spec:
  template:
    metadata:
      #@overlay/match missing_ok=True
      annotations:
        #@overlay/match missing_ok=True
        iam.amazonaws.com/role: #@ data.values.pod_role
    spec:
      containers:
      #@overlay/match by="name"
      - name: external-dns
        args:
        #@ if data.values.assumed_role != "":
        #@overlay/match by=lambda _,a,b: "--aws-assume-role=" in a, expects="0+"
        - #@ "--aws-assume-role={}".format(data.values.assumed_role)
        #@ end
        #@overlay/append
        - --aws-prefer-cname
        env:
        #@overlay/match by="name",when=1
        - name: CF_API_EMAIL
          value: #@ data.values.acme_email
        #@overlay/match by="name",when=1
        - name: AWS_DEFAULT_REGION
          value: #@ data.values.aws_region